### ISSUE TITLE
Example proxy request checks should include a entity definition

### ISSUE THREAD

**Issue by calebhailey** [sensu-community/monitoring-checks#24]
Example entity definitions should include the recommended/required metadata (i.e. labels & annotations).

**Comment by calebhailey** [comment]
Heh, we finally did this in the Sensu Go Workshop. Here's the example we settled on: 

```yaml
---
type: CheckConfig
api_version: core/v2
metadata:
  name: proxy-nslookup
spec:
  command: >-
    nslookup {{ .annotations.proxy_host }}
  runtime_assets: []
  publish: true
  subscriptions:
  - workshop
  interval: 30
  timeout: 10
  round_robin: true
  proxy_requests:
    entity_attributes:
      - entity.entity_class == "proxy"
      - entity.labels.proxy_type == "website"

---
type: Entity
api_version: core/v2
metadata:
  name: proxy-a
  labels:
    proxy_type: website
  annotations:
    proxy_host: sensu.io
spec:
  entity_class: proxy

---
type: Entity
api_version: core/v2
metadata:
  name: proxy-b
  labels:
    proxy_type: website
  annotations:
    proxy_host: google.com
spec:
  entity_class: proxy
```

it occurs to me that we could calls create a sub directory of proxy request examples as their own special class of checks.
